"""First teacher batch. Each row is a claim. The interpreter is separate."""

from __future__ import annotations

OWNER_MAP = {"texture": "ART", "district": "WORLD", "tick": "SIM", "save": "SYS"}
OWNER_RULE = {"op": "table", "key": "work", "map": OWNER_MAP}
AUTHORITY = ["RUNTIME", "TEST", "MEMORY", "HANDOFF"]
EDGES = [["draft", "submit_review"], ["review", "publish"]]


def _case(
    cid: str,
    lane: str,
    domain: str,
    subdomain: str,
    attack_family: str,
    mechanism_id: str,
    kind: str,
    question: str,
    options: list[str],
    answer: str,
    facts: dict,
    rule: dict,
    rationale: str,
    probe: bool = False,
) -> dict:
    return {
        "id": cid,
        "lane": lane,
        "domain": domain,
        "subdomain": subdomain,
        "attack_family": attack_family,
        "mechanism_id": mechanism_id,
        "kind": kind,
        "question": question,
        "options": list(options),
        "teacher_answer": answer,
        "teacher_confidence": 1.0,
        "teacher_rationale": rationale,
        "required_evidence": [f"deterministic:{rule['op']}"],
        "source_refs": ["jevh_teacher_swarm/verifiers/deterministic/interpret.py"],
        "facts": facts,
        "rule": rule,
        "probe": probe,
        "training_eligible": False,
    }


def authored_cases() -> list[dict]:
    rank = {"op": "rank", "order": AUTHORITY}
    edge = {"op": "edge", "allowed": EDGES, "if_true": "valid", "if_false": "invalid"}
    return [
        _case(
            "ts-token-old",
            "institutions",
            "trust",
            "permissions",
            "token_age",
            "expired_token_is_invalid",
            "permission_valid",
            "Token age is 5 hours. A token is invalid when age is greater than 0 hours. Is the permission valid?",
            ["valid", "invalid"],
            "invalid",
            {"age": 5, "limit": 0},
            {"op": "cmp", "left": "age", "right": "limit", "rel": "gt", "if_true": "invalid", "if_false": "valid"},
            "Age 5 is greater than 0, so the token is invalid.",
        ),
        _case(
            "ts-token-young",
            "institutions",
            "trust",
            "permissions",
            "token_age",
            "unexpired_token_stays_valid",
            "permission_valid",
            "Token age is 2 hours. A token is invalid when age is greater than 4 hours. Is the permission valid?",
            ["invalid", "valid"],
            "valid",
            {"age": 2, "limit": 4},
            {"op": "cmp", "left": "age", "right": "limit", "rel": "gt", "if_true": "invalid", "if_false": "valid"},
            "Age 2 is not greater than 4, so the token stays valid.",
        ),
        _case(
            "ts-role-low",
            "institutions",
            "trust",
            "permissions",
            "role_rank",
            "role_rank_threshold",
            "permission_valid",
            "Role rank is 1. The action requires rank 3. Permission is valid when role rank is greater than or equal to the required rank. Is the permission valid?",
            ["valid", "invalid"],
            "invalid",
            {"role": 1, "need": 3},
            {"op": "cmp", "left": "role", "right": "need", "rel": "ge", "if_true": "valid", "if_false": "invalid"},
            "Rank 1 does not meet required rank 3.",
        ),
        _case(
            "ts-role-high",
            "institutions",
            "trust",
            "permissions",
            "role_rank",
            "role_rank_threshold",
            "permission_valid",
            "Role rank is 3. The action requires rank 1. Permission is valid when role rank is greater than or equal to the required rank. Is the permission valid?",
            ["invalid", "valid"],
            "valid",
            {"role": 3, "need": 1},
            {"op": "cmp", "left": "role", "right": "need", "rel": "ge", "if_true": "valid", "if_false": "invalid"},
            "Rank 3 meets required rank 1.",
        ),
        _case(
            "ts-child-revoked",
            "institutions",
            "trust",
            "delegation",
            "parent_revoke",
            "parent_revocation_kills_child",
            "permission_valid",
            "Parent revoked flag is 1. Child age is 2 hours. The child is invalid when the flag is equal to 1. Is the permission valid?",
            ["valid", "invalid"],
            "invalid",
            {"flag": 1, "age": 2},
            {"op": "eq", "key": "flag", "value": 1, "if_true": "invalid", "if_false": "valid"},
            "Flag 1 revokes the child even though the child age is only 2 hours.",
        ),
        _case(
            "ts-spend-under",
            "institutions",
            "economy",
            "approval",
            "spend_bucket",
            "under_bucket_no_approval",
            "human_approval",
            "The request is 250 USD. The pre-approved bucket is 800 USD. Human approval is required when the request is greater than the bucket. Is human approval required?",
            ["required", "not_required"],
            "not_required",
            {"request": 250, "bucket": 800},
            {"op": "cmp", "left": "request", "right": "bucket", "rel": "gt", "if_true": "required", "if_false": "not_required"},
            "250 is not greater than 800.",
        ),
        _case(
            "ts-grant-low",
            "institutions",
            "trust",
            "privilege",
            "admin_grant",
            "privilege_grant_rank",
            "permission_valid",
            "Actor rank is 2. Admin grant requires rank 5. The grant is valid when actor rank is greater than or equal to the required rank. Is the grant valid?",
            ["valid", "invalid"],
            "invalid",
            {"actor": 2, "need": 5},
            {"op": "cmp", "left": "actor", "right": "need", "rel": "ge", "if_true": "valid", "if_false": "invalid"},
            "Actor rank 2 cannot grant a rank-5 admin action.",
        ),
        _case(
            "ts-self-scope",
            "institutions",
            "trust",
            "approval",
            "scope_gate",
            "self_scope_no_human",
            "human_approval",
            "Scope code is 1. The human gate is scope code 4. Human approval is required when scope code is greater than or equal to the gate. Is human approval required?",
            ["required", "not_required"],
            "not_required",
            {"scope": 1, "gate": 4},
            {"op": "cmp", "left": "scope", "right": "gate", "rel": "ge", "if_true": "required", "if_false": "not_required"},
            "Scope 1 is below gate 4.",
        ),
        _case(
            "ts-own-texture",
            "game_sim",
            "coordination",
            "owner",
            "worker_owner",
            "worker_policy_table",
            "owner",
            "Policy: texture is ART, district is WORLD, tick is SIM, save is SYS. Work is texture. Which worker owns this task?",
            ["WORLD", "ART", "SIM", "SYS"],
            "ART",
            {"work": "texture"},
            OWNER_RULE,
            "The work code texture maps to ART.",
        ),
        _case(
            "ts-own-district",
            "game_sim",
            "coordination",
            "owner",
            "worker_owner",
            "worker_policy_table",
            "owner",
            "Policy: texture is ART, district is WORLD, tick is SIM, save is SYS. Work is district. Which worker owns this task?",
            ["ART", "SYS", "WORLD", "SIM"],
            "WORLD",
            {"work": "district"},
            OWNER_RULE,
            "The work code district maps to WORLD.",
        ),
        _case(
            "ts-own-tick",
            "game_sim",
            "coordination",
            "owner",
            "worker_owner",
            "worker_policy_table",
            "owner",
            "Policy: texture is ART, district is WORLD, tick is SIM, save is SYS. Work is tick. Which worker owns this task?",
            ["SYS", "WORLD", "ART", "SIM"],
            "SIM",
            {"work": "tick"},
            OWNER_RULE,
            "The work code tick maps to SIM.",
        ),
        _case(
            "ts-own-save",
            "game_sim",
            "coordination",
            "owner",
            "worker_owner",
            "worker_policy_table",
            "owner",
            "Policy: texture is ART, district is WORLD, tick is SIM, save is SYS. Work is save. Which worker owns this task?",
            ["SIM", "ART", "SYS", "WORLD"],
            "SYS",
            {"work": "save"},
            OWNER_RULE,
            "The work code save maps to SYS.",
        ),
        _case(
            "ts-rev-soft",
            "game_sim",
            "simulation",
            "reversibility",
            "retention",
            "soft_retention_reversible",
            "action_reversible",
            "Retention is 30 days. The action is reversible when retention is greater than 0 days. Is the action reversible?",
            ["irreversible", "reversible"],
            "reversible",
            {"retention": 30, "limit": 0},
            {"op": "cmp", "left": "retention", "right": "limit", "rel": "gt", "if_true": "reversible", "if_false": "irreversible"},
            "Retention 30 is greater than 0.",
        ),
        _case(
            "ts-rev-none",
            "game_sim",
            "simulation",
            "reversibility",
            "zero_copies",
            "zero_copies_irreversible",
            "action_reversible",
            "Copies remaining is 0. The action is irreversible when copies remaining are equal to 0. Is the action reversible?",
            ["reversible", "irreversible"],
            "irreversible",
            {"copies": 0},
            {"op": "eq", "key": "copies", "value": 0, "if_true": "irreversible", "if_false": "reversible"},
            "Zero copies left cannot be undone.",
        ),
        _case(
            "ts-urgent-hf",
            "game_sim",
            "simulation",
            "repair",
            "health_factor",
            "health_factor_urgent",
            "repair_urgent",
            "Health factor is 1.01. Repair is urgent when the health factor is less than or equal to 1.05. Is repair urgent?",
            ["not_urgent", "urgent"],
            "urgent",
            {"hf": 1.01, "limit": 1.05},
            {"op": "cmp", "left": "hf", "right": "limit", "rel": "le", "if_true": "urgent", "if_false": "not_urgent"},
            "1.01 is within the urgent band at or below 1.05.",
        ),
        _case(
            "ts-disk-calm",
            "game_sim",
            "simulation",
            "repair",
            "disk_page",
            "disk_page_threshold",
            "repair_urgent",
            "Disk use is 42 percent. Repair is urgent when disk use is greater than or equal to 90 percent. Is repair urgent?",
            ["urgent", "not_urgent"],
            "not_urgent",
            {"used": 42, "page": 90},
            {"op": "cmp", "left": "used", "right": "page", "rel": "ge", "if_true": "urgent", "if_false": "not_urgent"},
            "42 is below the page threshold 90.",
        ),
        _case(
            "ts-lag-urgent",
            "game_sim",
            "simulation",
            "repair",
            "replica_lag",
            "lag_over_rpo",
            "repair_urgent",
            "Replica lag is 45 seconds. Repair is urgent when lag is greater than or equal to 5 seconds. Is repair urgent?",
            ["not_urgent", "urgent"],
            "urgent",
            {"lag": 45, "rpo": 5},
            {"op": "cmp", "left": "lag", "right": "rpo", "rel": "ge", "if_true": "urgent", "if_false": "not_urgent"},
            "Lag 45 has reached the 5 second repair line.",
        ),
        _case(
            "ts-edge-ok",
            "software",
            "state",
            "lifecycle",
            "state_edge",
            "state_machine_edges",
            "state_transition",
            "State is draft. Event is submit_review. Allowed edges are draft to submit_review, and review to publish. Is this transition valid?",
            ["invalid", "valid"],
            "valid",
            {"state": "draft", "event": "submit_review"},
            edge,
            "draft plus submit_review is an allowed edge.",
        ),
        _case(
            "ts-edge-skip",
            "software",
            "state",
            "lifecycle",
            "state_edge",
            "state_machine_edges",
            "state_transition",
            "State is draft. Event is publish. Allowed edges are draft to submit_review, and review to publish. Is this transition valid?",
            ["valid", "invalid"],
            "invalid",
            {"state": "draft", "event": "publish"},
            edge,
            "draft plus publish skips the only allowed draft edge.",
        ),
        _case(
            "ts-save-back",
            "software",
            "state",
            "save",
            "save_version",
            "save_version_monotonic",
            "save_valid",
            "The version sequence is 4 then 3. A save is valid when versions strictly increase. Is this save valid?",
            ["valid", "invalid"],
            "invalid",
            {"seq": [4, 3]},
            {"op": "monotonic", "key": "seq", "if_true": "valid", "if_false": "invalid"},
            "4 then 3 decreases.",
        ),
        _case(
            "ts-save-fwd",
            "software",
            "state",
            "save",
            "save_version",
            "save_version_monotonic",
            "save_valid",
            "The version sequence is 4 then 5. A save is valid when versions strictly increase. Is this save valid?",
            ["invalid", "valid"],
            "valid",
            {"seq": [4, 5]},
            {"op": "monotonic", "key": "seq", "if_true": "valid", "if_false": "invalid"},
            "4 then 5 increases.",
        ),
        _case(
            "ts-dup-id",
            "software",
            "state",
            "identity",
            "duplicate_id",
            "duplicate_id",
            "duplicate_id",
            "Candidate id is 77. Existing ids are 77 and 12. The candidate is taken when it is contained in the existing ids. Is the candidate taken?",
            ["free", "taken"],
            "taken",
            {"candidate": 77, "existing": [77, 12]},
            {"op": "contains", "key": "existing", "item": 77, "if_true": "taken", "if_false": "free"},
            "77 is already present.",
        ),
        _case(
            "ts-free-id",
            "software",
            "state",
            "identity",
            "duplicate_id",
            "duplicate_id",
            "duplicate_id",
            "Candidate id is 9. Existing ids are 77 and 12. The candidate is taken when it is contained in the existing ids. Is the candidate taken?",
            ["taken", "free"],
            "free",
            {"candidate": 9, "existing": [77, 12]},
            {"op": "contains", "key": "existing", "item": 9, "if_true": "taken", "if_false": "free"},
            "9 is not among 77 and 12.",
        ),
        _case(
            "ts-lock-bad",
            "software",
            "concurrency",
            "locks",
            "lock_order",
            "lock_acquire_ascending",
            "lock_order",
            "Lock ids were acquired as 2 then 1. Acquisition is valid when ids strictly increase. Is this acquisition valid?",
            ["valid", "invalid"],
            "invalid",
            {"seq": [2, 1]},
            {"op": "monotonic", "key": "seq", "if_true": "valid", "if_false": "invalid"},
            "2 then 1 is not ascending.",
        ),
        _case(
            "ts-lock-ok",
            "software",
            "concurrency",
            "locks",
            "lock_order",
            "lock_acquire_ascending",
            "lock_order",
            "Lock ids were acquired as 1 then 2. Acquisition is valid when ids strictly increase. Is this acquisition valid?",
            ["invalid", "valid"],
            "valid",
            {"seq": [1, 2]},
            {"op": "monotonic", "key": "seq", "if_true": "valid", "if_false": "invalid"},
            "1 then 2 is ascending.",
        ),
        _case(
            "ts-budget-over",
            "software",
            "economy",
            "budget",
            "budget_remaining",
            "budget_remaining",
            "budget",
            "Request is 40. Remaining is 30. The request exceeds budget when request is greater than remaining. Does the request exceed budget?",
            ["within", "exceed"],
            "exceed",
            {"request": 40, "remaining": 30},
            {"op": "cmp", "left": "request", "right": "remaining", "rel": "gt", "if_true": "exceed", "if_false": "within"},
            "40 is greater than 30.",
        ),
        _case(
            "ts-budget-ok",
            "software",
            "economy",
            "budget",
            "budget_remaining",
            "budget_remaining",
            "budget",
            "Request is 10. Remaining is 30. The request exceeds budget when request is greater than remaining. Does the request exceed budget?",
            ["exceed", "within"],
            "within",
            {"request": 10, "remaining": 30},
            {"op": "cmp", "left": "request", "right": "remaining", "rel": "gt", "if_true": "exceed", "if_false": "within"},
            "10 is not greater than 30.",
        ),
        _case(
            "ts-cons-ok",
            "software",
            "economy",
            "conservation",
            "quantity_sum",
            "quantity_conservation",
            "conservation",
            "Parts are 4 and 6. Total is 10. Quantities are conserved when the parts sum to the total. Are the quantities conserved?",
            ["violated", "conserved"],
            "conserved",
            {"parts": [4, 6], "total": 10},
            {"op": "sum_eq", "parts": "parts", "total": "total", "if_true": "conserved", "if_false": "violated"},
            "4 plus 6 equals 10.",
        ),
        _case(
            "ts-cons-bad",
            "software",
            "economy",
            "conservation",
            "quantity_sum",
            "quantity_conservation",
            "conservation",
            "Parts are 4 and 7. Total is 10. Quantities are conserved when the parts sum to the total. Are the quantities conserved?",
            ["conserved", "violated"],
            "violated",
            {"parts": [4, 7], "total": 10},
            {"op": "sum_eq", "parts": "parts", "total": "total", "if_true": "conserved", "if_false": "violated"},
            "4 plus 7 is 11, not 10.",
        ),
        _case(
            "ts-stock-low",
            "software",
            "economy",
            "inventory",
            "stock_floor",
            "stock_floor",
            "conservation",
            "Quantity is 0. Floor is 1. Quantity is valid when it is greater than or equal to the floor. Is the quantity valid?",
            ["valid", "invalid"],
            "invalid",
            {"qty": 0, "floor": 1},
            {"op": "cmp", "left": "qty", "right": "floor", "rel": "ge", "if_true": "valid", "if_false": "invalid"},
            "0 is below floor 1.",
        ),
        _case(
            "ts-ship-ok",
            "epistemics",
            "causality",
            "orders",
            "prerequisite",
            "causal_prerequisite",
            "event_causally_valid",
            "Priors include payment_captured. Shipping is valid when priors contain payment_captured. Is the shipment causally valid?",
            ["invalid", "valid"],
            "valid",
            {"priors": ["order_created", "payment_captured"]},
            {"op": "contains", "key": "priors", "item": "payment_captured", "if_true": "valid", "if_false": "invalid"},
            "payment_captured is already in the priors.",
        ),
        _case(
            "ts-refund-bare",
            "epistemics",
            "causality",
            "orders",
            "prerequisite",
            "causal_prerequisite",
            "event_causally_valid",
            "Priors are only a ping. A refund is valid when priors contain order_created. Is the refund causally valid?",
            ["valid", "invalid"],
            "invalid",
            {"priors": ["ping"]},
            {"op": "contains", "key": "priors", "item": "order_created", "if_true": "valid", "if_false": "invalid"},
            "order_created is absent.",
        ),
        _case(
            "ts-effect-early",
            "epistemics",
            "causality",
            "time",
            "causal_time",
            "causal_time",
            "event_causally_valid",
            "Effect time is 1. Cause time is 2. The effect is causally valid when effect time is greater than cause time. Is the effect causally valid?",
            ["valid", "invalid"],
            "invalid",
            {"effect": 1, "cause": 2},
            {"op": "cmp", "left": "effect", "right": "cause", "rel": "gt", "if_true": "valid", "if_false": "invalid"},
            "Effect time 1 is not after cause time 2.",
        ),
        _case(
            "ts-effect-late",
            "epistemics",
            "causality",
            "time",
            "causal_time",
            "causal_time",
            "event_causally_valid",
            "Effect time is 8. Cause time is 3. The effect is causally valid when effect time is greater than cause time. Is the effect causally valid?",
            ["invalid", "valid"],
            "valid",
            {"effect": 8, "cause": 3},
            {"op": "cmp", "left": "effect", "right": "cause", "rel": "gt", "if_true": "valid", "if_false": "invalid"},
            "Effect time 8 is after cause time 3.",
        ),
        _case(
            "ts-reach-yes",
            "epistemics",
            "causality",
            "graph",
            "reachability",
            "directed_reachability",
            "reachability",
            "Directed edges are A to B and B to C. Start is A. Goal is C. Is the goal reachable?",
            ["unreachable", "reachable"],
            "reachable",
            {"edges": [["A", "B"], ["B", "C"]], "start": "A", "goal": "C"},
            {"op": "reach", "if_true": "reachable", "if_false": "unreachable"},
            "A reaches B and B reaches C.",
        ),
        _case(
            "ts-reach-no",
            "epistemics",
            "causality",
            "graph",
            "reachability",
            "directed_reachability",
            "reachability",
            "Directed edges are A to B and B to C. Start is A. Goal is D. Is the goal reachable?",
            ["reachable", "unreachable"],
            "unreachable",
            {"edges": [["A", "B"], ["B", "C"]], "start": "A", "goal": "D"},
            {"op": "reach", "if_true": "reachable", "if_false": "unreachable"},
            "No edge reaches D.",
        ),
        _case(
            "ts-cycle-yes",
            "epistemics",
            "causality",
            "graph",
            "cycle",
            "directed_cycle",
            "cycle",
            "Directed edges are A to B and B to A. Does the graph contain a cycle?",
            ["no", "yes"],
            "yes",
            {"edges": [["A", "B"], ["B", "A"]]},
            {"op": "cycle", "if_true": "yes", "if_false": "no"},
            "A and B point at each other.",
        ),
        _case(
            "ts-cycle-no",
            "epistemics",
            "causality",
            "graph",
            "cycle",
            "directed_cycle",
            "cycle",
            "Directed edges are A to B and B to C. Does the graph contain a cycle?",
            ["yes", "no"],
            "no",
            {"edges": [["A", "B"], ["B", "C"]]},
            {"op": "cycle", "if_true": "yes", "if_false": "no"},
            "The chain does not return.",
        ),
        _case(
            "ts-rank-both",
            "epistemics",
            "memory",
            "authority",
            "source_rank",
            "authority_lattice",
            "authority",
            "Present sources are RUNTIME and MEMORY. Highest authority first is RUNTIME, then TEST, then MEMORY, then HANDOFF. Which source wins?",
            ["MEMORY", "HANDOFF", "RUNTIME", "TEST"],
            "RUNTIME",
            {"present": ["RUNTIME", "MEMORY"]},
            rank,
            "RUNTIME outranks MEMORY.",
        ),
        _case(
            "ts-rank-signed",
            "epistemics",
            "memory",
            "authority",
            "source_rank",
            "authority_lattice",
            "authority",
            "Present sources are RUNTIME and MEMORY. MEMORY timestamp is 20. RUNTIME timestamp is 10. MEMORY signed flag is 1. Highest authority first is RUNTIME, then TEST, then MEMORY, then HANDOFF. Which source wins?",
            ["MEMORY", "RUNTIME", "TEST", "HANDOFF"],
            "RUNTIME",
            {"present": ["RUNTIME", "MEMORY"], "memory_ts": 20, "runtime_ts": 10, "signed": 1},
            rank,
            "A newer signed MEMORY record still loses to RUNTIME.",
        ),
        _case(
            "ts-rank-memory",
            "epistemics",
            "memory",
            "authority",
            "source_rank",
            "authority_lattice",
            "authority",
            "Present sources are MEMORY only. Highest authority first is RUNTIME, then TEST, then MEMORY, then HANDOFF. Which source wins?",
            ["RUNTIME", "TEST", "HANDOFF", "MEMORY"],
            "MEMORY",
            {"present": ["MEMORY"]},
            rank,
            "MEMORY is the only present source.",
        ),
        _case(
            "ts-quorum-met",
            "epistemics",
            "institutions",
            "quorum",
            "vote_quorum",
            "quorum_threshold",
            "quorum",
            "Votes are 2. Need is 2. Quorum is met when votes are greater than or equal to the need. Is quorum met?",
            ["unmet", "met"],
            "met",
            {"votes": 2, "need": 2},
            {"op": "cmp", "left": "votes", "right": "need", "rel": "ge", "if_true": "met", "if_false": "unmet"},
            "2 votes meet a need of 2.",
        ),
        _case(
            "ts-quorum-miss",
            "epistemics",
            "institutions",
            "quorum",
            "vote_quorum",
            "quorum_threshold",
            "quorum",
            "Votes are 1. Need is 2. Quorum is met when votes are greater than or equal to the need. Is quorum met?",
            ["met", "unmet"],
            "unmet",
            {"votes": 1, "need": 2},
            {"op": "cmp", "left": "votes", "right": "need", "rel": "ge", "if_true": "met", "if_false": "unmet"},
            "1 vote does not meet a need of 2.",
        ),
        _case(
            "ts-ttl-probe",
            "epistemics",
            "memory",
            "freshness",
            "ttl_arithmetic",
            "fresh_within_limit",
            "source_stale",
            "Blob age is 11 minutes. Limit is 60 minutes. The source is stale when age is greater than the limit. Is the source stale?",
            ["stale", "fresh"],
            "fresh",
            {"age": 11, "limit": 60},
            {"op": "cmp", "left": "age", "right": "limit", "rel": "gt", "if_true": "stale", "if_false": "fresh"},
            "11 is not greater than 60. Persistence probe of the known fresh-source failure.",
            probe=True,
        ),
        _case(
            "ts-spend-probe",
            "institutions",
            "economy",
            "approval",
            "spend_threshold",
            "approval_spend_over",
            "human_approval",
            "Requested spend is 12000 USD. The approval threshold is 1000 USD. Human approval is required when spend is greater than the threshold. Is human approval required?",
            ["not_required", "required"],
            "required",
            {"spend": 12000, "threshold": 1000},
            {"op": "cmp", "left": "spend", "right": "threshold", "rel": "gt", "if_true": "required", "if_false": "not_required"},
            "12000 is greater than 1000. Persistence probe of the known spend failure.",
            probe=True,
        ),
        _case(
            "ts-canon-probe",
            "epistemics",
            "memory",
            "canonical",
            "noncanonical_noise",
            "nonauthoritative_not_contradiction",
            "canonical_contradicted",
            "Canonical quantity is 4. Replica quantity is 4. A non-canonical note says 0. State is consistent when canonical quantity equals replica quantity. Is canonical state consistent?",
            ["contradicted", "consistent"],
            "consistent",
            {"canonical": 4, "replica": 4, "note": 0},
            {"op": "cmp", "left": "canonical", "right": "replica", "rel": "eq", "if_true": "consistent", "if_false": "contradicted"},
            "Canonical and replica both say 4. The note is not part of the equality. Persistence probe.",
            probe=True,
        ),
        _case(
            "ts-past-limit",
            "epistemics",
            "memory",
            "freshness",
            "ttl_arithmetic",
            "past_limit_is_stale",
            "source_stale",
            "Record age is 9 hours. Max age is 6 hours. The source is stale when age is greater than max age. Is the source stale?",
            ["fresh", "stale"],
            "stale",
            {"age": 9, "max_age": 6},
            {"op": "cmp", "left": "age", "right": "max_age", "rel": "gt", "if_true": "stale", "if_false": "fresh"},
            "9 is greater than 6, so the source is stale. Opposite of the fresh-source bug.",
        ),
    ]
