"""Prebuilt wall of atomic student questions. Labels come from the interpreter."""

from __future__ import annotations

from jevh_teacher_swarm.verifiers.deterministic.interpret import interpret

# id, mechanism, kind, family, lane, template, yes, no, rel, (a,b) pairs
# yes is the label when the comparison holds.
_CMP = [
    ("lease", "lease_past_life", "source_stale", "lease", "software", "The lease age is {a} hours. Its life is {b} hours. The lease is dead when age is greater than life. Is the lease dead?", "dead", "alive", "gt", ((9, 6), (4, 6))),
    ("visa", "visa_past_window", "permission_valid", "visa", "institutions", "The visa age is {a} days. The window is {b} days. The visa is expired when age is greater than the window. Is the visa expired?", "expired", "current", "gt", ((12, 7), (3, 7))),
    ("hold", "hold_still_open", "action_reversible", "hold", "economy", "The hold age is {a} minutes. Release is due at {b} minutes. The hold is open when age is less than the due time. Is the hold open?", "open", "released", "lt", ((5, 20), (25, 20))),
    ("pool", "pool_over_cap", "budget", "pool", "software", "Borrowed sockets are {a}. The pool cap is {b}. The pool is over cap when borrowed is greater than the cap. Is the pool over cap?", "over", "within", "gt", ((40, 32), (12, 32))),
    ("fee", "fee_fits_balance", "budget", "fee", "economy", "The fee is {a} cents. The balance is {b} cents. The fee fits when the fee is less than or equal to the balance. Does the fee fit?", "fits", "short", "le", ((80, 80), (90, 80))),
    ("lag", "lag_breaks_rpo", "repair_urgent", "lag", "software", "Replica lag is {a} seconds. The RPO is {b} seconds. Repair is due when lag is greater than or equal to the RPO. Is repair due?", "due", "calm", "ge", ((45, 5), (2, 5))),
    ("disk", "disk_below_page", "repair_urgent", "disk", "software", "Disk use is {a} percent. The page line is {b} percent. A page is due when use is greater than or equal to the line. Is a page due?", "due", "calm", "ge", ((93, 90), (42, 90))),
    ("votes", "quorum_met", "quorum", "votes", "institutions", "Votes in hand are {a}. The motion needs {b}. It carries when votes are greater than or equal to the need. Does the motion carry?", "carries", "fails", "ge", ((2, 2), (1, 2))),
    ("seats", "license_seats", "budget", "seats", "institutions", "Assigned seats are {a}. Purchased seats are {b}. The license is oversold when assigned is greater than purchased. Is it oversold?", "oversold", "covered", "gt", ((11, 10), (8, 10))),
    ("inbox", "unread_backlog", "repair_urgent", "inbox", "software", "Unread alerts are {a}. The desk cap is {b}. The desk is overloaded when unread is greater than the cap. Is the desk overloaded?", "overloaded", "fine", "gt", ((30, 12), (4, 12))),
    ("cert", "cert_inside_life", "permission_valid", "cert", "institutions", "Certificate age is {a} days. The life is {b} days. It is still valid when age is less than the life. Is it still valid?", "valid", "expired", "lt", ((10, 90), (100, 90))),
    ("nonce", "nonce_inside_skew", "event_causally_valid", "nonce", "epistemics", "Clock skew is {a} seconds. Allowed skew is {b} seconds. The stamp is acceptable when skew is less than or equal to the allowance. Is the stamp acceptable?", "acceptable", "rejected", "le", ((30, 60), (90, 60))),
    ("retry", "retry_budget_left", "budget", "retry", "software", "Attempts used are {a}. The attempt cap is {b}. Another try is allowed when used is less than the cap. Is another try allowed?", "allowed", "spent", "lt", ((2, 5), (5, 5))),
    ("temp", "temp_over_limit", "repair_urgent", "temp", "game_sim", "Core temperature is {a} C. The cutout is {b} C. Cutout is required when temperature is greater than the cutout. Is cutout required?", "required", "not_required", "gt", ((92, 85), (70, 85))),
    ("battery", "battery_below_floor", "repair_urgent", "battery", "game_sim", "Battery charge is {a} percent. The floor is {b} percent. A charge warning is due when charge is less than the floor. Is a warning due?", "due", "fine", "lt", ((8, 15), (40, 15))),
    ("stock", "stock_at_reorder", "conservation", "stock", "economy", "Units on hand are {a}. The reorder point is {b}. A reorder is due when units are less than or equal to the point. Is a reorder due?", "due", "stocked", "le", ((5, 5), (18, 5))),
    ("tax", "tax_included_fits", "budget", "tax", "economy", "The gross charge is {a} cents. The card cap is {b} cents. The charge clears when gross is less than or equal to the cap. Does the charge clear?", "clears", "declined", "le", ((1000, 1200), (1500, 1200))),
    ("span", "span_over_deadline", "repair_urgent", "span", "software", "Elapsed work is {a} ms. The deadline is {b} ms. The span is late when elapsed is greater than the deadline. Is the span late?", "late", "on_time", "gt", ((80, 50), (20, 50))),
    ("epoch", "epoch_moved_forward", "save_valid", "epoch", "software", "The new epoch is {a}. The current epoch is {b}. The bump is legal when the new epoch is greater than the current epoch. Is the bump legal?", "legal", "illegal", "gt", ((8, 7), (7, 7))),
    ("offset", "consumer_caught_up", "repair_urgent", "offset", "software", "Consumer offset is {a}. Log end is {b}. The consumer is caught up when offset is greater than or equal to the log end. Is it caught up?", "caught_up", "behind", "ge", ((40, 40), (12, 40))),
    ("wal", "wal_lag_hot", "repair_urgent", "wal", "software", "Unarchived WAL is {a} MB. The alarm is {b} MB. Archive is late when unarchived is greater than the alarm. Is archive late?", "late", "current", "gt", ((80, 32), (10, 32))),
    ("inode", "inode_below_line", "repair_urgent", "inode", "software", "Inode use is {a} percent. The line is {b} percent. An inode page is due when use is greater than or equal to the line. Is a page due?", "due", "calm", "ge", ((91, 90), (22, 90))),
    ("fd", "fd_under_limit", "budget", "fd", "software", "Open files are {a}. The process limit is {b}. There is headroom when open files are less than the limit. Is there headroom?", "headroom", "exhausted", "lt", ((100, 1024), (1024, 1024))),
    ("thread", "thread_pool_saturated", "repair_urgent", "thread", "software", "Busy workers are {a}. Pool size is {b}. The pool is saturated when busy workers are greater than or equal to the size. Is it saturated?", "saturated", "spare", "ge", ((8, 8), (3, 8))),
    ("queue", "queue_over_workers", "repair_urgent", "queue", "software", "Waiting jobs are {a}. Live workers are {b}. The queue is backed up when jobs are greater than workers. Is the queue backed up?", "backed_up", "flowing", "gt", ((14, 6), (2, 6))),
    ("canary", "canary_error_hot", "repair_urgent", "canary", "software", "Canary errors are {a}. The gate is {b}. The canary fails when errors are greater than the gate. Does the canary fail?", "fails", "passes", "gt", ((7, 2), (1, 2))),
    ("burn", "budget_burned", "repair_urgent", "burn", "software", "Budget used is {a} percent. The freeze line is {b} percent. A freeze is required when used is greater than or equal to the line. Is a freeze required?", "required", "not_required", "ge", ((100, 100), (40, 100))),
    ("silence", "silence_still_active", "repair_urgent", "silence", "software", "Silence age is {a} minutes. The silence lasts {b} minutes. It is still active when age is less than the duration. Is it still active?", "active", "ended", "lt", ((5, 30), (40, 30))),
    ("ack", "ack_past_due", "repair_urgent", "ack", "institutions", "Minutes since page are {a}. Ack is required by minute {b}. The ack is late when minutes are greater than the requirement. Is the ack late?", "late", "in_time", "gt", ((15, 5), (2, 5))),
    ("rotate", "key_inside_overlap", "permission_valid", "key", "institutions", "Hours since rotation are {a}. Overlap is {b} hours. The old key still works when hours are less than or equal to the overlap. Does the old key work?", "works", "retired", "le", ((2, 24), (48, 24))),
    ("audience", "audience_exact", "permission_valid", "audience", "institutions", "Presented audience code is {a}. Expected audience code is {b}. The token fits when the codes are equal. Does the token fit?", "fits", "rejected", "eq", ((7, 7), (7, 9))),
    ("issuer", "issuer_exact", "permission_valid", "issuer", "institutions", "Presented issuer code is {a}. Expected issuer code is {b}. The token is trusted when the codes are equal. Is the token trusted?", "trusted", "untrusted", "eq", ((4, 4), (4, 1))),
    ("scope", "scope_rank_enough", "permission_valid", "scope", "institutions", "Actor scope rank is {a}. The call requires rank {b}. The call is permitted when actor rank is greater than or equal to the requirement. Is the call permitted?", "permitted", "denied", "ge", ((3, 1), (1, 3))),
    ("mfa", "mfa_age_fresh", "permission_valid", "mfa", "institutions", "MFA age is {a} minutes. The fresh window is {b} minutes. MFA is fresh when age is less than the window. Is MFA fresh?", "fresh", "stale", "lt", ((4, 15), (20, 15))),
    ("geo", "geo_code_match", "permission_valid", "geo", "institutions", "Request region code is {a}. The allow code is {b}. Entry is allowed when the codes are equal. Is entry allowed?", "allowed", "blocked", "eq", ((44, 44), (44, 33))),
    ("maintenance", "inside_maintenance", "repair_urgent", "maintenance", "software", "Minute of day is {a}. Maintenance starts at minute {b}. Maintenance has started when the minute is greater than or equal to the start. Has it started?", "started", "waiting", "ge", ((130, 120), (40, 120))),
    ("freeze", "change_freeze_on", "human_approval", "freeze", "institutions", "Freeze flag is {a}. A freeze is on when the flag is equal to 1. Is the freeze on?", "on", "off", "eq", ((1, 1), (0, 1))),
    ("holdout", "experiment_holdout", "quorum", "holdout", "institutions", "Bucket is {a}. Holdout is the buckets below {b}. This bucket is holdout when the bucket number is less than the cut. Is it holdout?", "holdout", "exposed", "lt", ((3, 10), (15, 10))),
    ("sticky", "sticky_same_bucket", "quorum", "sticky", "software", "Saved bucket is {a}. Current bucket is {b}. The assignment is sticky when the buckets are equal. Is it sticky?", "sticky", "reshuffled", "eq", ((6, 6), (6, 8))),
    ("shadow", "shadow_diff_hot", "repair_urgent", "shadow", "software", "Mismatched shadow replies are {a}. The tolerance is {b}. Shadow is unhealthy when mismatches are greater than the tolerance. Is shadow unhealthy?", "unhealthy", "healthy", "gt", ((9, 1), (0, 1))),
    ("contract", "contract_breaks", "state_transition", "contract", "software", "Missing required fields are {a}. A break is any count greater than {b}. Is the contract broken?", "broken", "intact", "gt", ((2, 0), (0, 0))),
    ("schema", "schema_newer_reader", "save_valid", "schema", "software", "Writer schema is {a}. Reader schema is {b}. The reader can parse when reader schema is greater than or equal to the writer schema. Can the reader parse?", "parses", "rejects", "ge", ((5, 4), (3, 4))),
    ("migration", "migration_version_gap", "save_valid", "migration", "software", "Applied migration is {a}. The target migration is {b}. A gap remains when applied is less than target. Does a gap remain?", "gap", "level", "lt", ((4, 7), (7, 7))),
    ("lockwait", "lock_wait_exceeded", "repair_urgent", "lock", "software", "Lock wait is {a} ms. The wait cap is {b} ms. The wait has failed when it is greater than the cap. Has the wait failed?", "failed", "waiting", "gt", ((500, 200), (50, 200))),
    ("idle", "idle_transaction_hot", "repair_urgent", "idle", "software", "Idle transaction age is {a} seconds. The cap is {b} seconds. It should be killed when age is greater than the cap. Should it be killed?", "kill", "keep", "gt", ((90, 30), (10, 30))),
    ("xid", "xid_wrap_risk", "repair_urgent", "xid", "software", "XID age is {a} million. The warn line is {b} million. Wraparound risk is present when age is greater than or equal to the line. Is there wraparound risk?", "risk", "safe", "ge", ((180, 150), (20, 150))),
    ("bloat", "table_bloat_hot", "repair_urgent", "bloat", "software", "Dead tuple percent is {a}. The vacuum line is {b}. Vacuum is due when dead percent is greater than or equal to the line. Is vacuum due?", "due", "defer", "ge", ((35, 20), (5, 20))),
    ("backup", "backup_older_than_rpo", "source_stale", "backup", "software", "Hours since backup are {a}. The RPO is {b} hours. The backup is too old when hours are greater than the RPO. Is the backup too old?", "too_old", "fresh_enough", "gt", ((30, 24), (6, 24))),
    ("snapshot", "snapshot_ready", "state_transition", "snapshot", "software", "Ready replicas of the snapshot are {a}. One is enough, and the bar is {b}. The snapshot is ready when replicas are greater than or equal to the bar. Is it ready?", "ready", "pending", "ge", ((1, 1), (0, 1))),
    ("restore", "restore_lag_ok", "repair_urgent", "restore", "software", "Restore lag is {a} minutes. The drill limit is {b} minutes. The drill passes when lag is less than or equal to the limit. Does the drill pass?", "passes", "fails", "le", ((15, 20), (45, 20))),
    ("fence", "fence_epoch_higher", "permission_valid", "fence", "software", "Request epoch is {a}. The fenced epoch is {b}. The write is allowed when the request epoch is greater than the fence. Is the write allowed?", "allowed", "fenced", "gt", ((6, 5), (5, 5))),
    ("witness", "witness_sees_quorum", "quorum", "witness", "software", "Votes including the witness are {a}. Quorum is {b}. Quorum holds when votes are greater than or equal to the quorum. Does quorum hold?", "holds", "lost", "ge", ((2, 2), (1, 2))),
    ("sync", "sync_replica_short", "repair_urgent", "sync", "software", "Synchronous replicas are {a}. The minimum is {b}. The set is short when replicas are less than the minimum. Is the set short?", "short", "full", "lt", ((1, 2), (2, 2))),
    ("async", "async_lag_over", "repair_urgent", "async", "software", "Async lag is {a} MB. Promotion refuses above {b} MB. Promotion is refused when lag is greater than the line. Is promotion refused?", "refused", "allowed", "gt", ((80, 16), (4, 16))),
    ("pdb", "pdb_would_break", "repair_urgent", "pdb", "software", "Ready pods are {a}. Minimum available is {b}. A disruption breaks the budget when ready is less than or equal to the minimum. Would it break the budget?", "breaks", "safe", "le", ((2, 2), (5, 2))),
    ("surge", "surge_room", "budget", "surge", "software", "Extra pods are {a}. Surge max is {b}. There is surge room when extra pods are less than the max. Is there surge room?", "room", "capped", "lt", ((1, 2), (2, 2))),
    ("cpu", "cpu_over_request", "repair_urgent", "cpu", "software", "CPU millicores used are {a}. The request is {b}. The pod is over request when used is greater than the request. Is it over request?", "over", "inside", "gt", ((900, 500), (200, 500))),
    ("mem", "memory_over_limit", "repair_urgent", "mem", "software", "Memory MB used is {a}. The limit is {b} MB. The pod is over limit when used is greater than the limit. Is it over limit?", "over", "inside", "gt", ((520, 512), (400, 512))),
    ("evict", "eviction_pressure", "repair_urgent", "evict", "software", "Node memory percent is {a}. Eviction starts at {b} percent. Eviction pressure is on when percent is greater than or equal to the start. Is pressure on?", "on", "off", "ge", ((95, 90), (50, 90))),
    ("taint", "taint_blocks", "permission_valid", "taint", "software", "Pod tolerate code is {a}. The node taint code is {b}. The pod may land when the codes are equal. May the pod land?", "lands", "blocked", "eq", ((3, 3), (3, 8))),
    ("zone", "zone_skew", "repair_urgent", "zone", "software", "Pods in the heavy zone are {a}. The skew cap is {b}. Skew is too high when the heavy zone is greater than the cap. Is skew too high?", "too_high", "balanced", "gt", ((6, 4), (3, 4))),
    ("pv", "volume_bound", "state_transition", "pv", "software", "Bound claims are {a}. The claim needs {b}. The volume is bound when claims are greater than or equal to the need. Is the volume bound?", "bound", "pending", "ge", ((1, 1), (0, 1))),
    ("expand", "volume_expand_done", "state_transition", "expand", "software", "Current GB are {a}. Requested GB are {b}. Expansion is finished when current is greater than or equal to requested. Is expansion finished?", "finished", "pending", "ge", ((200, 200), (100, 200))),
    ("lifecycle", "object_past_expire", "source_stale", "lifecycle", "software", "Object age is {a} days. Expiry is {b} days. The object is due to expire when age is greater than or equal to expiry. Is it due?", "due", "kept", "ge", ((30, 30), (10, 30))),
    ("multipart", "multipart_abandoned", "repair_urgent", "multipart", "software", "Upload age is {a} days. Abort is due after {b} days. Abort is due when age is greater than the limit. Is abort due?", "due", "active", "gt", ((8, 7), (2, 7))),
    ("replicate", "replication_behind", "repair_urgent", "replicate", "software", "Replication lag is {a} minutes. The alarm is {b} minutes. Replication is behind when lag is greater than the alarm. Is it behind?", "behind", "current", "gt", ((25, 10), (3, 10))),
    ("trail", "trail_gap", "source_stale", "trail", "institutions", "Minutes since the last audit event are {a}. The gap alarm is {b} minutes. The trail is gapped when minutes are greater than the alarm. Is the trail gapped?", "gapped", "flowing", "gt", ((40, 15), (5, 15))),
    ("drift", "config_drift", "canonical_contradicted", "drift", "software", "Desired replicas are {a}. Observed replicas are {b}. Drift exists when desired and observed are not equal. Does drift exist?", "drift", "settled", "ne", ((3, 2), (3, 3))),
    ("generation", "status_stale_gen", "source_stale", "generation", "software", "Observed generation is {a}. Metadata generation is {b}. Status is stale when observed is less than metadata. Is status stale?", "stale", "fresh", "lt", ((4, 5), (5, 5))),
    ("conflict", "resource_version_clash", "state_transition", "conflict", "software", "Write version is {a}. Stored version is {b}. The write conflicts when the versions are not equal. Does it conflict?", "conflict", "clean", "ne", ((9, 8), (9, 9))),
    ("unique", "unique_key_taken", "duplicate_id", "unique", "software", "Matching rows are {a}. A duplicate is any count greater than {b}. Is the key a duplicate?", "duplicate", "free", "gt", ((1, 0), (0, 0))),
    ("fk", "fk_parent_missing", "event_causally_valid", "fk", "software", "Matching parents are {a}. A live parent is a count greater than {b}. Is a parent present?", "present", "missing", "gt", ((1, 0), (0, 0))),
    ("null", "nulls_blocked", "state_transition", "null", "software", "Null inserts are {a}. The column allows {b} nulls. The insert is rejected when nulls are greater than the allowance. Is it rejected?", "rejected", "accepted", "gt", ((1, 0), (0, 0))),
    ("check", "check_amount_nonneg", "conservation", "check", "economy", "The posted amount is {a}. The floor is {b}. The amount is legal when it is greater than or equal to the floor. Is the amount legal?", "legal", "illegal", "ge", ((4, 1), (0, 1))),
    ("rls", "rls_tenant_match", "permission_valid", "rls", "institutions", "Row tenant code is {a}. Session tenant code is {b}. The row is visible when the codes are equal. Is the row visible?", "visible", "hidden", "eq", ((12, 12), (12, 4))),
    ("grant", "grant_covers_action", "permission_valid", "grant", "institutions", "Grant rank is {a}. The action rank is {b}. The grant covers the action when grant rank is greater than or equal to the action rank. Does it cover the action?", "covers", "misses", "ge", ((5, 2), (1, 2))),
    ("scp", "scp_deny", "permission_valid", "scp", "institutions", "SCP deny flag is {a}. A deny is active when the flag equals {b}. Is the deny active?", "active", "inactive", "eq", ((1, 1), (0, 1))),
    ("boundary", "boundary_blocks", "permission_valid", "boundary", "institutions", "Boundary rank is {a}. The request rank is {b}. The boundary blocks the request when boundary rank is less than the request rank. Does it block?", "blocks", "allows", "lt", ((2, 5), (5, 5))),
    ("sessionpol", "session_policy_short", "permission_valid", "session", "institutions", "Session rank is {a}. Identity rank is {b}. The session cuts access when session rank is less than identity rank. Does the session cut access?", "cuts", "keeps", "lt", ((1, 4), (4, 4))),
    ("quota", "account_quota_hit", "budget", "quota", "software", "Running functions are {a}. The account quota is {b}. The quota is hit when running is greater than or equal to the quota. Is the quota hit?", "hit", "open", "ge", ((100, 100), (40, 100))),
    ("reserved", "reserved_concurrency_full", "budget", "reserved", "software", "In-flight calls are {a}. Reserved concurrency is {b}. The reserve is full when in-flight is greater than or equal to reserved. Is it full?", "full", "open", "ge", ((20, 20), (7, 20))),
    ("spot", "spot_interrupted", "repair_urgent", "spot", "software", "Interruption notices are {a}. Any notice greater than {b} means the instance is interrupted. Is it interrupted?", "interrupted", "running", "gt", ((1, 0), (0, 0))),
    ("az", "az_capacity_short", "repair_urgent", "az", "software", "Free instances in the zone are {a}. The launch needs {b}. Capacity is short when free is less than the need. Is capacity short?", "short", "enough", "lt", ((0, 1), (3, 1))),
    ("spread", "spread_failed", "repair_urgent", "spread", "software", "Hosts already used are {a}. Distinct hosts required are {b}. Spread has failed when used hosts are less than the requirement. Has spread failed?", "failed", "met", "lt", ((1, 2), (2, 2))),
    ("cron", "cron_overlap_blocked", "state_transition", "cron", "software", "Active runs are {a}. Overlap allows {b}. A new run is forbidden when active runs are greater than or equal to the allowance. Is a new run forbidden?", "forbidden", "allowed", "ge", ((1, 1), (0, 1))),
    ("deadline", "job_past_deadline", "repair_urgent", "deadline", "software", "Job age is {a} seconds. The active deadline is {b} seconds. The job is past deadline when age is greater than the deadline. Is it past deadline?", "past", "inside", "gt", ((700, 600), (100, 600))),
    ("completions", "job_complete", "state_transition", "completions", "software", "Succeeded pods are {a}. Completions required are {b}. The job is complete when succeeded is greater than or equal to required. Is the job complete?", "complete", "running", "ge", ((3, 3), (1, 3))),
    ("parallel", "parallel_room", "budget", "parallel", "software", "Running pods are {a}. Parallelism is {b}. Another pod may start when running is less than parallelism. May another pod start?", "may", "wait", "lt", ((2, 4), (4, 4))),
    ("ttljob", "finished_job_expired", "source_stale", "ttljob", "software", "Seconds since finish are {a}. TTL is {b} seconds. The job record is expired when seconds are greater than or equal to the TTL. Is the record expired?", "expired", "kept", "ge", ((120, 120), (10, 120))),
    ("readiness", "ready_after_grace", "state_transition", "readiness", "software", "Seconds since start are {a}. Grace is {b} seconds. Readiness counts when seconds are greater than or equal to grace. Does readiness count?", "counts", "ignored", "ge", ((12, 10), (3, 10))),
    ("restart", "restart_limit_hit", "repair_urgent", "restart", "software", "Restarts are {a}. The backoff limit is {b}. The job has crashed out when restarts are greater than the limit. Has it crashed out?", "crashed", "retrying", "gt", ((6, 5), (2, 5))),
    ("liveness", "liveness_failed", "repair_urgent", "liveness", "software", "Failed probes are {a}. The failure threshold is {b}. The container is unready when failed probes are greater than or equal to the threshold. Is it unready?", "unready", "ready", "ge", ((3, 3), (1, 3))),
    ("startup", "startup_still_pending", "state_transition", "startup", "software", "Startup probe successes are {a}. One success is the bar at {b}. Startup is done when successes are greater than or equal to the bar. Is startup done?", "done", "pending", "ge", ((1, 1), (0, 1))),
    ("preempt", "preempt_lower_priority", "repair_urgent", "preempt", "software", "Victim priority is {a}. Pending pod priority is {b}. The victim may be preempted when its priority is less than the pending pod. May it be preempted?", "preempted", "kept", "lt", ((10, 100), (100, 100))),
    ("cordon", "cordon_blocks_new", "permission_valid", "cordon", "software", "Unschedulable flag is {a}. New pods are blocked when the flag equals {b}. Are new pods blocked?", "blocked", "allowed", "eq", ((1, 1), (0, 1))),
    ("drain", "drain_finished", "state_transition", "drain", "software", "Pods still on the node are {a}. Drain is finished when pods are less than or equal to {b}. Is drain finished?", "finished", "busy", "le", ((0, 0), (3, 0))),
    ("pdbmin", "pdb_min_met", "repair_urgent", "pdbmin", "software", "Available pods are {a}. The minimum is {b}. The budget is healthy when available is greater than the minimum. Is the budget healthy?", "healthy", "tight", "gt", ((4, 2), (2, 2))),
    ("hpa", "hpa_scale_up", "repair_urgent", "hpa", "software", "Current replicas are {a}. Desired replicas are {b}. Scale-up is required when current is less than desired. Is scale-up required?", "required", "not_required", "lt", ((2, 5), (5, 5))),
    ("vpa", "vpa_request_low", "repair_urgent", "vpa", "software", "Requested millicores are {a}. Recommended millicores are {b}. The request is low when requested is less than recommended. Is the request low?", "low", "enough", "lt", ((100, 400), (400, 400))),
    ("netpol", "netpol_default_deny", "permission_valid", "netpol", "software", "Allow rules matching the flow are {a}. A flow is denied when matching rules are less than or equal to {b}. Is the flow denied?", "denied", "allowed", "le", ((0, 0), (1, 0))),
    ("ingress", "ingress_host_match", "permission_valid", "ingress", "software", "Request host code is {a}. Rule host code is {b}. The rule matches when the codes are equal. Does the rule match?", "matches", "misses", "eq", ((15, 15), (15, 2))),
    ("tlsver", "tls_too_old", "permission_valid", "tls", "software", "Client TLS minor version is {a}. The minimum minor version is {b}. The client is too old when its version is less than the minimum. Is the client too old?", "too_old", "ok", "lt", ((2, 3), (3, 3))),
    ("certexp", "cert_not_yet", "permission_valid", "certexp", "software", "Days until not_before are {a}. A certificate is not yet valid when days until not_before are greater than {b}. Is it not yet valid?", "not_yet", "in_window", "gt", ((2, 0), (0, 0))),
    ("san", "san_name_match", "permission_valid", "san", "software", "Presented name code is {a}. Certificate name code is {b}. The name matches when the codes are equal. Does the name match?", "matches", "mismatch", "eq", ((21, 21), (21, 22))),
    ("replay", "nonce_replayed", "event_causally_valid", "replay", "epistemics", "Prior uses of this nonce are {a}. A replay is any prior use greater than {b}. Is this a replay?", "replay", "fresh", "gt", ((1, 0), (0, 0))),
    ("bodysig", "body_hash_match", "canonical_contradicted", "body", "epistemics", "Computed body hash code is {a}. Signed hash code is {b}. The body matches when the codes are equal. Does the body match?", "matches", "tampered", "eq", ((88, 88), (88, 13))),
    ("kid", "key_id_known", "permission_valid", "kid", "institutions", "Header key id is {a}. The known key id is {b}. The key is known when the ids are equal. Is the key known?", "known", "unlisted", "eq", ((5, 5), (5, 6))),
    ("nbf", "token_before_nbf", "permission_valid", "nbf", "institutions", "Seconds until not_before are {a}. The token is early when seconds until not_before are greater than {b}. Is the token early?", "early", "usable", "gt", ((30, 0), (0, 0))),
    ("exp", "token_past_exp", "permission_valid", "exp", "institutions", "Seconds past expiry are {a}. The token is expired when seconds past expiry are greater than {b}. Is the token expired?", "expired", "live", "gt", ((5, 0), (0, 0))),
    ("pkce", "pkce_verifier_match", "permission_valid", "pkce", "institutions", "Verifier hash code is {a}. Challenge code is {b}. The verifier matches when the codes are equal. Does it match?", "matches", "rejects", "eq", ((42, 42), (42, 7))),
    ("redirect", "redirect_allowlisted", "permission_valid", "redirect", "institutions", "Redirect id is {a}. The allowlist id is {b}. The redirect is allowed when the ids are equal. Is it allowed?", "allowed", "blocked", "eq", ((3, 3), (3, 9))),
    ("origin", "origin_allowed", "permission_valid", "origin", "institutions", "Origin id is {a}. The allowed origin id is {b}. The origin is allowed when the ids are equal. Is the origin allowed?", "allowed", "blocked", "eq", ((11, 11), (11, 12))),
    ("cookie", "cookie_past_max_age", "source_stale", "cookie", "software", "Cookie age is {a} seconds. Max-age is {b} seconds. The cookie is stale when age is greater than max-age. Is the cookie stale?", "stale", "fresh", "gt", ((400, 300), (100, 300))),
    ("etag", "etag_matches", "canonical_contradicted", "etag", "software", "Client etag code is {a}. Current etag code is {b}. The cache can be reused when the codes are equal. Can the cache be reused?", "reused", "refetch", "eq", ((17, 17), (17, 18))),
    ("ims", "not_modified", "source_stale", "ims", "software", "Resource timestamp is {a}. The if-modified-since timestamp is {b}. The resource is unchanged when its timestamp is less than or equal to the condition. Is it unchanged?", "unchanged", "changed", "le", ((10, 12), (15, 12))),
    ("signedurl", "signed_url_expired", "permission_valid", "signedurl", "software", "Seconds past the signed expiry are {a}. The URL is expired when seconds past expiry are greater than {b}. Is the URL expired?", "expired", "live", "gt", ((1, 0), (0, 0))),
    ("range", "range_inside_object", "state_transition", "range", "software", "Range end is {a}. Object length is {b}. The range is inside the object when the end is less than the length. Is the range inside?", "inside", "outside", "lt", ((10, 20), (20, 20))),
    ("idem", "idempotency_body_clash", "duplicate_id", "idem", "software", "Stored body code is {a}. New body code is {b}. The key is in conflict when the codes are not equal. Is the key in conflict?", "conflict", "replay_ok", "ne", ((5, 6), (5, 5))),
    ("dlq", "dlq_after_tries", "repair_urgent", "dlq", "software", "Delivery tries are {a}. The dead-letter line is {b}. The message is dead when tries are greater than or equal to the line. Is the message dead?", "dead", "retry", "ge", ((5, 5), (2, 5))),
    ("outbox", "outbox_unpublished", "state_transition", "outbox", "software", "Unpublished outbox rows are {a}. A backlog exists when rows are greater than {b}. Is there a backlog?", "backlog", "clear", "gt", ((3, 0), (0, 0))),
    ("applied", "inbox_already_applied", "duplicate_id", "applied", "software", "Prior applies of this key are {a}. It is a duplicate when prior applies are greater than {b}. Is it a duplicate?", "duplicate", "new", "gt", ((1, 0), (0, 0))),
    ("saga", "saga_needs_compensate", "action_reversible", "saga", "software", "Failed steps are {a}. Compensation starts when failed steps are greater than {b}. Is compensation required?", "required", "not_required", "gt", ((1, 0), (0, 0))),
    ("reserve", "reservation_expired", "source_stale", "reserve", "economy", "Reservation age is {a} minutes. The hold is {b} minutes. The reservation is expired when age is greater than the hold. Is it expired?", "expired", "held", "gt", ((20, 15), (5, 15))),
    ("capture", "capture_within_auth", "budget", "capture", "economy", "Capture amount is {a} cents. Authorized amount is {b} cents. Capture is allowed when the amount is less than or equal to the authorization. Is capture allowed?", "allowed", "refused", "le", ((500, 500), (700, 500))),
    ("refund", "refund_within_captured", "budget", "refund", "economy", "Refund requested is {a} cents. Captured net is {b} cents. The refund is allowed when the request is less than or equal to the net. Is the refund allowed?", "allowed", "refused", "le", ((200, 350), (400, 350))),
    ("shipfree", "free_shipping", "economy", "ship", "economy", "Cart total is {a} cents. Free shipping starts at {b} cents. Shipping is free when the cart is greater than or equal to the start. Is shipping free?", "free", "charged", "ge", ((2500, 2000), (1500, 2000))),
    ("cancel", "cancel_window_open", "action_reversible", "cancel", "economy", "Minutes since purchase are {a}. The cancel window is {b} minutes. Cancel is still open when minutes are less than or equal to the window. Is cancel open?", "open", "closed", "le", ((10, 30), (45, 30))),
    ("return", "return_window_open", "action_reversible", "return", "economy", "Days since delivery are {a}. The return window is {b} days. A return is open when days are less than or equal to the window. Is a return open?", "open", "closed", "le", ((14, 30), (40, 30))),
    ("warranty", "warranty_live", "action_reversible", "warranty", "economy", "Months since sale are {a}. Warranty length is {b} months. Warranty is live when months are less than or equal to the length. Is warranty live?", "live", "ended", "le", ((6, 12), (18, 12))),
    ("lot", "lot_expired", "source_stale", "lot", "economy", "Lot age is {a} days. Shelf life is {b} days. The lot is expired when age is greater than shelf life. Is the lot expired?", "expired", "usable", "gt", ((40, 30), (10, 30))),
    ("atp", "atp_covers_order", "conservation", "atp", "economy", "Available units are {a}. The order wants {b}. The order is coverable when available is greater than or equal to the want. Is the order coverable?", "coverable", "short", "ge", ((8, 8), (3, 8))),
    ("cutoff", "past_ship_cutoff", "repair_urgent", "cutoff", "economy", "Hour of day is {a}. The ship cutoff hour is {b}. The order missed cutoff when the hour is greater than the cutoff. Did it miss cutoff?", "missed", "made", "gt", ((16, 15), (14, 15))),
    ("sla", "sla_clock_over", "repair_urgent", "sla", "institutions", "Open minutes are {a}. The SLA is {b} minutes. The SLA is breached when open minutes are greater than the SLA. Is the SLA breached?", "breached", "inside", "gt", ((130, 120), (40, 120))),
    ("sev", "sev1_pages", "repair_urgent", "sev", "institutions", "Severity rank is {a}. Paging starts at rank {b} or below, and a page is due when rank is less than or equal to that line. Is a page due?", "due", "ticket_only", "le", ((1, 2), (4, 2))),
    ("flap", "alert_flapping", "repair_urgent", "flap", "software", "State changes in the window are {a}. Flap starts above {b}. Is the alert flapping?", "flapping", "steady", "gt", ((6, 3), (1, 3))),
    ("inhibit", "inhibit_active", "repair_urgent", "inhibit", "software", "Matching inhibit rules are {a}. The alert is suppressed when matching rules are greater than {b}. Is the alert suppressed?", "suppressed", "firing", "gt", ((1, 0), (0, 0))),
    ("deploy", "freeze_during_incident", "human_approval", "deploy", "institutions", "Open critical incidents are {a}. Deploys are frozen when open incidents are greater than {b}. Are deploys frozen?", "frozen", "open", "gt", ((1, 0), (0, 0))),
    ("rollback", "rollback_first", "repair_urgent", "rollback", "software", "Error rate after the ship is {a} percent. The rollback line is {b} percent. Rollback comes first when the error rate is greater than or equal to the line. Does rollback come first?", "first", "later", "ge", ((5, 2), (0, 2))),
    ("flag", "kill_switch_on", "repair_urgent", "flag", "software", "Kill switch flag is {a}. Traffic stops when the flag equals {b}. Is traffic stopped?", "stopped", "flowing", "eq", ((1, 1), (0, 1))),
    ("compat", "reader_too_old", "save_valid", "compat", "software", "Reader version is {a}. Minimum reader version is {b}. The reader is too old when its version is less than the minimum. Is the reader too old?", "too_old", "compatible", "lt", ((2, 3), (3, 3))),
    ("partition", "partition_lag_hot", "repair_urgent", "partition", "software", "Hottest partition lag is {a} messages. The page line is {b} messages. A page is due when lag is greater than or equal to the line. Is a page due?", "due", "calm", "ge", ((5000, 1000), (20, 1000))),
    ("commit", "offset_committed", "state_transition", "commit", "software", "Committed offset is {a}. Processed offset is {b}. The commit is caught up when committed is greater than or equal to processed. Is the commit caught up?", "caught_up", "open", "ge", ((10, 10), (8, 10))),
    ("rebalance", "rebalance_in_progress", "state_transition", "rebalance", "software", "Members still joining are {a}. Rebalance is in progress when members still joining are greater than {b}. Is rebalance in progress?", "in_progress", "stable", "gt", ((2, 0), (0, 0))),
    ("producer", "sequence_gap", "event_causally_valid", "producer", "software", "Next sequence is {a}. Expected sequence is {b}. There is a gap when next is greater than expected. Is there a gap?", "gap", "contiguous", "gt", ((8, 5), (5, 5))),
    ("hwm", "read_past_hwm", "event_causally_valid", "hwm", "software", "Requested offset is {a}. High watermark is {b}. The read is past the watermark when the offset is greater than the watermark. Is the read past it?", "past", "visible", "gt", ((12, 9), (9, 9))),
    ("compaction", "tombstone_due", "source_stale", "compaction", "software", "Tombstone age is {a} hours. Delete retention is {b} hours. The tombstone can be dropped when age is greater than or equal to retention. Can it be dropped?", "dropped", "kept", "ge", ((24, 24), (2, 24))),
    ("retention", "log_past_retention", "source_stale", "retention", "software", "Segment age is {a} hours. Retention is {b} hours. The segment is deletable when age is greater than retention. Is the segment deletable?", "deletable", "retained", "gt", ((72, 48), (12, 48))),
    ("exactly", "txn_marker_complete", "state_transition", "exactly", "software", "Commit markers are {a}. A finished transaction has markers greater than or equal to {b}. Is the transaction finished?", "finished", "open", "ge", ((1, 1), (0, 1))),
    ("bulkhead", "bulkhead_full", "budget", "bulkhead", "software", "Calls in the bulkhead are {a}. The bulkhead size is {b}. The bulkhead is full when calls are greater than or equal to the size. Is it full?", "full", "open", "ge", ((16, 16), (4, 16))),
    ("breaker", "breaker_open", "repair_urgent", "breaker", "software", "Recent failures are {a}. The open threshold is {b}. The breaker is open when failures are greater than or equal to the threshold. Is the breaker open?", "open", "closed", "ge", ((5, 5), (1, 5))),
    ("shed", "shed_load", "repair_urgent", "shed", "software", "Queue wait is {a} ms. Shed starts at {b} ms. Load should be shed when wait is greater than or equal to the start. Should load be shed?", "shed", "keep", "ge", ((250, 200), (40, 200))),
    ("tokenbucket", "bucket_has_token", "budget", "tokenbucket", "software", "Tokens in the bucket are {a}. A call spends 1 and is allowed when tokens are greater than or equal to {b}. Is the call allowed?", "allowed", "throttled", "ge", ((1, 1), (0, 1))),
    ("leaky", "leaky_over_level", "budget", "leaky", "software", "Bucket level is {a}. The bucket height is {b}. The bucket overflows when level is greater than height. Does it overflow?", "overflows", "holds", "gt", ((12, 10), (6, 10))),
    ("concurrency", "concurrency_at_cap", "budget", "concurrency", "software", "Active requests are {a}. The concurrency cap is {b}. New work is rejected when active is greater than or equal to the cap. Is new work rejected?", "rejected", "accepted", "ge", ((32, 32), (8, 32))),
    ("deadlineleft", "deadline_exhausted", "repair_urgent", "deadlineleft", "software", "Remaining budget is {a} ms. A call is out of time when remaining budget is less than or equal to {b}. Is the call out of time?", "out", "inside", "le", ((0, 0), (40, 0))),
    ("child", "child_exceeds_parent", "event_causally_valid", "child", "software", "Child timeout is {a} ms. Parent timeout is {b} ms. The child exceeds the parent when the child timeout is greater than the parent timeout. Does the child exceed the parent?", "exceeds", "fits", "gt", ((800, 500), (200, 500))),
    ("hedge", "hedge_too_soon", "repair_urgent", "hedge", "software", "Wait so far is {a} ms. Hedge delay is {b} ms. A hedge is early when the wait is less than the delay. Is a hedge early?", "early", "due", "lt", ((20, 80), (90, 80))),
    ("cachettl", "cache_entry_fresh", "source_stale", "cachettl", "software", "Entry age is {a} seconds. TTL is {b} seconds. The entry is fresh when age is less than the TTL. Is the entry fresh?", "fresh", "stale", "lt", ((8, 30), (40, 30))),
    ("swr", "swr_window", "source_stale", "swr", "software", "Seconds past TTL are {a}. Stale-while-revalidate allows {b} seconds. A stale serve is allowed when seconds past TTL are less than or equal to the allowance. Is a stale serve allowed?", "allowed", "must_block", "le", ((5, 10), (20, 10))),
    ("origin5", "origin_error_budget", "repair_urgent", "origin", "software", "Origin failures are {a}. The shed line is {b}. The edge should shed when failures are greater than or equal to the line. Should the edge shed?", "shed", "proxy", "ge", ((8, 5), (1, 5))),
    ("ratelimit", "rate_over_quota", "budget", "rate", "software", "Requests this second are {a}. The quota is {b}. The caller is over quota when requests are greater than the quota. Is the caller over quota?", "over", "inside", "gt", ((21, 20), (10, 20))),
    ("burst", "burst_spent", "budget", "burst", "software", "Burst used is {a}. Burst size is {b}. Burst remains when used is less than the size. Does burst remain?", "remains", "spent", "lt", ((3, 10), (10, 10))),
    ("daily", "daily_cap_hit", "budget", "daily", "economy", "Spent today is {a} cents. The daily cap is {b} cents. The cap is hit when spent is greater than or equal to the cap. Is the cap hit?", "hit", "open", "ge", ((5000, 5000), (1200, 5000))),
    ("velocity", "velocity_hot", "human_approval", "velocity", "economy", "Payments in the hour are {a}. The review line is {b}. A human review is required when payments are greater than or equal to the line. Is review required?", "required", "not_required", "ge", ((6, 5), (2, 5))),
    ("3ds", "step_up_required", "human_approval", "3ds", "economy", "Charge is {a} cents. Step-up starts at {b} cents. Step-up is required when the charge is greater than or equal to the start. Is step-up required?", "required", "not_required", "ge", ((2500, 2000), (500, 2000))),
    ("avs", "avs_mismatch", "permission_valid", "avs", "economy", "AVS result code is {a}. A match is code {b}. The address matches when the codes are equal. Does the address match?", "matches", "mismatch", "eq", ((1, 1), (2, 1))),
    ("cvv", "cvv_match", "permission_valid", "cvv", "economy", "CVV result code is {a}. A match is code {b}. The CVV matches when the codes are equal. Does the CVV match?", "matches", "mismatch", "eq", ((1, 1), (0, 1))),
    ("authage", "auth_still_capturable", "action_reversible", "authage", "economy", "Hours since auth are {a}. Capture is allowed for {b} hours. Capture is still allowed when hours are less than or equal to the window. Is capture still allowed?", "allowed", "expired", "le", ((12, 168), (200, 168))),
    ("settled", "settlement_final", "action_reversible", "settled", "economy", "Days since settlement are {a}. A void is allowed for {b} days. A void is still open when days are less than or equal to the window. Is a void still open?", "open", "final", "le", ((0, 0), (2, 0))),
    ("chargeback", "chargeback_window", "action_reversible", "chargeback", "economy", "Days since capture are {a}. The dispute window is {b} days. A dispute is in window when days are less than or equal to the window. Is the dispute in window?", "in_window", "closed", "le", ((30, 120), (200, 120))),
    ("kyc", "kyc_level_enough", "permission_valid", "kyc", "institutions", "Customer level is {a}. The product requires level {b}. The customer qualifies when level is greater than or equal to the requirement. Does the customer qualify?", "qualifies", "short", "ge", ((2, 2), (1, 2))),
    ("doc", "document_current", "permission_valid", "doc", "institutions", "Document age is {a} days. The document life is {b} days. The document is current when age is less than the life. Is the document current?", "current", "expired", "lt", ((20, 365), (400, 365))),
    ("sanctions", "sanctions_hit", "permission_valid", "sanctions", "institutions", "List hits are {a}. A block is any hit greater than {b}. Is the party blocked?", "blocked", "clear", "gt", ((1, 0), (0, 0))),
    ("residency", "residency_match", "permission_valid", "residency", "institutions", "Data region code is {a}. Required region code is {b}. Residency is satisfied when the codes are equal. Is residency satisfied?", "satisfied", "violated", "eq", ((3, 3), (3, 1))),
    ("purpose", "purpose_allowed", "permission_valid", "purpose", "institutions", "Stated purpose code is {a}. The consented purpose code is {b}. The purpose is allowed when the codes are equal. Is the purpose allowed?", "allowed", "denied", "eq", ((2, 2), (2, 5))),
    ("consent", "consent_recorded", "permission_valid", "consent", "institutions", "Consent records are {a}. Processing is allowed when records are greater than {b}. Is processing allowed?", "allowed", "denied", "gt", ((1, 0), (0, 0))),
    ("minimization", "fields_over_purpose", "permission_valid", "minimization", "institutions", "Collected fields are {a}. The purpose allows {b}. The collection is excessive when collected fields are greater than the allowance. Is it excessive?", "excessive", "minimal", "gt", ((12, 4), (3, 4))),
    ("holdlegal", "legal_hold_blocks_delete", "action_reversible", "holdlegal", "institutions", "Active legal holds are {a}. Deletion is blocked when holds are greater than {b}. Is deletion blocked?", "blocked", "allowed", "gt", ((1, 0), (0, 0))),
    ("dsar", "dsar_overdue", "repair_urgent", "dsar", "institutions", "Days since the request are {a}. The response limit is {b} days. The request is overdue when days are greater than the limit. Is it overdue?", "overdue", "in_time", "gt", ((31, 30), (10, 30))),
    ("encrypt", "encryption_off", "repair_urgent", "encrypt", "software", "Encrypted blocks are {a}. A volume is unprotected when encrypted blocks are less than or equal to {b}. Is the volume unprotected?", "unprotected", "protected", "le", ((0, 0), (4, 0))),
    ("public", "bucket_public", "permission_valid", "public", "software", "Public ACL grants are {a}. The bucket is public when grants are greater than {b}. Is the bucket public?", "public", "private", "gt", ((1, 0), (0, 0))),
    ("kms", "kms_key_disabled", "permission_valid", "kms", "software", "Enabled key flag is {a}. The key is usable when the flag equals {b}. Is the key usable?", "usable", "disabled", "eq", ((1, 1), (0, 1))),
    ("vpce", "vpce_required_met", "permission_valid", "vpce", "software", "Request came from the required endpoint flag {a}. Access is allowed when the flag equals {b}. Is access allowed?", "allowed", "denied", "eq", ((1, 1), (0, 1))),
    ("tag", "tag_gate_match", "permission_valid", "tag", "institutions", "Resource tag code is {a}. The required tag code is {b}. The gate passes when the codes are equal. Does the gate pass?", "passes", "fails", "eq", ((9, 9), (9, 2))),
    ("ou", "ou_scp_inherited", "permission_valid", "ou", "institutions", "Deny statements inherited are {a}. The account is denied when inherited denies are greater than {b}. Is the account denied?", "denied", "allowed", "gt", ((1, 0), (0, 0))),
    ("hours", "inside_business_hours", "human_approval", "hours", "institutions", "Hour of day is {a}. The desk closes at hour {b}. The desk is open when the hour is less than the close. Is the desk open?", "open", "closed", "lt", ((9, 17), (18, 17))),
    ("pager", "secondary_after_wait", "repair_urgent", "pager", "institutions", "Minutes without ack are {a}. Secondary starts at minute {b}. Secondary should be paged when minutes are greater than or equal to the start. Should secondary be paged?", "page", "wait", "ge", ((10, 10), (3, 10))),
    ("statuspage", "customer_visible", "repair_urgent", "statuspage", "institutions", "Customer-facing failures are {a}. A status notice is required when failures are greater than {b}. Is a status notice required?", "required", "not_required", "gt", ((1, 0), (0, 0))),
    ("detect", "detection_slow", "repair_urgent", "detect", "institutions", "Minutes to detect are {a}. The detect target is {b} minutes. Detection was slow when minutes are greater than the target. Was detection slow?", "slow", "met", "gt", ((25, 5), (2, 5))),
    ("mitigate", "mitigation_slow", "repair_urgent", "mitigate", "institutions", "Minutes to mitigate are {a}. The mitigate target is {b} minutes. Mitigation was slow when minutes are greater than the target. Was mitigation slow?", "slow", "met", "gt", ((70, 30), (10, 30))),
    ("postmortem", "postmortem_required", "human_approval", "postmortem", "institutions", "Severity rank is {a}. A postmortem is required when rank is less than or equal to {b}. Is a postmortem required?", "required", "not_required", "le", ((1, 2), (4, 2))),
    ("action", "action_overdue", "repair_urgent", "action", "institutions", "Days past the action due date are {a}. It is overdue when days past due are greater than {b}. Is it overdue?", "overdue", "on_time", "gt", ((3, 0), (0, 0))),
    ("toil", "toil_high", "repair_urgent", "toil", "software", "Manual touches this week are {a}. The toil line is {b}. Toil is high when touches are greater than the line. Is toil high?", "high", "normal", "gt", ((14, 5), (2, 5))),
    ("noise", "noisy_alert", "repair_urgent", "noise", "software", "Pages with no action are {a}. The noise line is {b}. The alert is noisy when such pages are greater than or equal to the line. Is the alert noisy?", "noisy", "signal", "ge", ((4, 3), (0, 3))),
    ("symptom", "paging_symptom", "repair_urgent", "symptom", "software", "User-visible failures are {a}. A symptom page is due when failures are greater than {b}. Is a symptom page due?", "due", "not_due", "gt", ((3, 0), (0, 0))),
    ("cause", "cause_page_blocked", "repair_urgent", "cause", "software", "Direct user failures are {a}. A cause-only signal may page when user failures are greater than {b}. May this cause-only signal page?", "may", "must_not", "gt", ((1, 0), (0, 0))),
    ("fastburn", "fast_burn_page", "repair_urgent", "fastburn", "software", "One-hour burn percent is {a}. The fast-burn page line is {b}. A page is due when burn is greater than or equal to the line. Is a page due?", "due", "watch", "ge", ((14, 10), (2, 10))),
    ("slowburn", "slow_burn_ticket", "repair_urgent", "slowburn", "software", "Six-hour burn percent is {a}. The ticket line is {b}. A ticket is due when burn is greater than or equal to the line. Is a ticket due?", "due", "quiet", "ge", ((5, 2), (0, 2))),
    ("bothburn", "both_windows_hot", "repair_urgent", "bothburn", "software", "Windows over their lines are {a}. A page requires greater than {b} hot windows. Is a page required?", "required", "not_required", "gt", ((2, 1), (1, 1))),
    ("season", "above_seasonal", "repair_urgent", "season", "software", "Current errors are {a}. The seasonal band top is {b}. The point is above the band when current is greater than the top. Is it above the band?", "above", "inside", "gt", ((40, 25), (10, 25))),
    ("correlate", "ship_overlap", "repair_urgent", "correlate", "software", "Minutes between the ship and the jump are {a}. They overlap when minutes are less than or equal to {b}. Do they overlap?", "overlap", "separate", "le", ((5, 15), (40, 15))),
    ("capacity", "scale_not_restart", "repair_urgent", "capacity", "software", "Saturation percent is {a}. Scale-out starts at {b} percent. Scale-out is the move when saturation is greater than or equal to the start. Is scale-out the move?", "scale", "hold", "ge", ((85, 70), (20, 70))),
    ("leak", "restart_for_leak", "repair_urgent", "leak", "software", "Heap growth MB is {a}. The leak line is {b} MB. A restart is warranted when growth is greater than or equal to the line. Is a restart warranted?", "warranted", "not_warranted", "ge", ((800, 500), (40, 500))),
    ("corrupt", "do_not_restart_corrupt", "repair_urgent", "corrupt", "software", "Checksum failures are {a}. Restart is the wrong tool when checksum failures are greater than {b}. Is restart the wrong tool?", "wrong_tool", "fine_to_restart", "gt", ((3, 0), (0, 0))),
    ("hardware", "failover_hardware", "repair_urgent", "hardware", "software", "Disk errors are {a}. Failover is required when disk errors are greater than {b}. Is failover required?", "required", "not_required", "gt", ((1, 0), (0, 0))),
    ("deadlock", "deadlock_not_scale", "repair_urgent", "deadlock", "software", "Deadlocks this minute are {a}. Scaling is the wrong move when deadlocks are greater than {b}. Is scaling the wrong move?", "wrong_move", "scale_ok", "gt", ((2, 0), (0, 0))),
    ("overload", "shed_when_overloaded", "repair_urgent", "overload", "software", "Rejected accepts are {a}. Shedding is appropriate when rejects are greater than {b}. Is shedding appropriate?", "appropriate", "not_yet", "gt", ((10, 0), (0, 0))),
    ("query", "query_bug_not_failover", "repair_urgent", "query", "software", "Identical wrong results are {a}. Failover will not help when wrong results are greater than {b}. Will failover fail to help?", "no_help", "might_help", "gt", ((4, 0), (0, 0))),
]


def _cmp_holds(rel: str, left: int, right: int) -> bool:
    if rel == "gt":
        return left > right
    if rel == "ge":
        return left >= right
    if rel == "lt":
        return left < right
    if rel == "le":
        return left <= right
    if rel == "eq":
        return left == right
    if rel == "ne":
        return left != right
    raise ValueError(rel)


def _raw(cid: str, mech: str, kind: str, family: str, lane: str, question: str, options: list[str], answer: str, facts: dict, rule: dict, rationale: str) -> dict:
    return {
        "id": cid,
        "lane": lane,
        "domain": kind,
        "subdomain": family,
        "attack_family": family,
        "mechanism_id": mech,
        "kind": kind,
        "question": question,
        "options": options,
        "teacher_answer": answer,
        "teacher_confidence": 1.0,
        "teacher_rationale": rationale,
        "required_evidence": [f"deterministic:{rule['op']}"],
        "source_refs": ["jevh_teacher_swarm/verifiers/deterministic/interpret.py"],
        "facts": facts,
        "rule": rule,
        "probe": False,
        "training_eligible": False,
    }


def wall_cases() -> list[dict]:
    rows: list[dict] = []
    for prefix, mech, kind, family, lane, template, yes, no, rel, pairs in _CMP:
        for index, (left, right) in enumerate(pairs):
            holds = _cmp_holds(rel, left, right)
            answer = yes if holds else no
            question = template.format(a=left, b=right)
            facts = {"a": left, "b": right}
            rule = {
                "op": "cmp",
                "left": "a",
                "right": "b",
                "rel": rel,
                "if_true": yes,
                "if_false": no,
            }
            # Interpreter agrees with the arithmetic; do not trust the hand label alone.
            if interpret(rule, facts) != answer:
                raise RuntimeError(f"wall label mismatch {prefix}")
            options = [no, yes] if index % 2 == 0 else [yes, no]
            rows.append(
                _raw(
                    f"w-{prefix}-{index}",
                    mech,
                    kind,
                    family,
                    lane,
                    question,
                    options,
                    answer,
                    facts,
                    rule,
                    f"Comparison {rel} on {left} and {right} selects {answer}.",
                )
            )
    rows.extend(_structural())
    return rows


def _structural() -> list[dict]:
    rank = {"op": "rank", "order": ["RUNTIME", "TEST", "MEMORY", "HANDOFF"]}
    edge = {
        "op": "edge",
        "allowed": [["draft", "review"], ["review", "published"]],
        "if_true": "valid",
        "if_false": "invalid",
    }
    owner = {"op": "table", "key": "work", "map": {"shader": "ART", "plot": "WORLD", "tick": "SIM", "migrate": "SYS"}}
    return [
        _raw(
            "w-rank-live",
            "runtime_beats_signed_memory",
            "authority",
            "rank",
            "epistemics",
            "Present sources are RUNTIME and MEMORY. MEMORY is signed and newer. Highest authority first is RUNTIME, then TEST, then MEMORY, then HANDOFF. Which source wins?",
            ["MEMORY", "RUNTIME", "HANDOFF", "TEST"],
            "RUNTIME",
            {"present": ["RUNTIME", "MEMORY"]},
            rank,
            "RUNTIME outranks a newer signed MEMORY record.",
        ),
        _raw(
            "w-rank-only-memory",
            "only_present_source_wins",
            "authority",
            "rank",
            "epistemics",
            "The only present source is HANDOFF. Highest authority first is RUNTIME, then TEST, then MEMORY, then HANDOFF. Which source wins?",
            ["RUNTIME", "MEMORY", "TEST", "HANDOFF"],
            "HANDOFF",
            {"present": ["HANDOFF"]},
            rank,
            "HANDOFF is the only present source.",
        ),
        _raw(
            "w-edge-review",
            "draft_review_publish_edge",
            "state_transition",
            "edge",
            "software",
            "State is review. Event is published. Allowed edges are draft to review, and review to published. Is this transition valid?",
            ["invalid", "valid"],
            "valid",
            {"state": "review", "event": "published"},
            edge,
            "review to published is allowed.",
        ),
        _raw(
            "w-edge-skip",
            "draft_review_publish_edge",
            "state_transition",
            "edge",
            "software",
            "State is draft. Event is published. Allowed edges are draft to review, and review to published. Is this transition valid?",
            ["valid", "invalid"],
            "invalid",
            {"state": "draft", "event": "published"},
            edge,
            "draft to published skips review.",
        ),
        _raw(
            "w-own-shader",
            "work_code_owner",
            "owner",
            "owner",
            "game_sim",
            "Policy: shader is ART, plot is WORLD, tick is SIM, migrate is SYS. Work is shader. Which worker owns this task?",
            ["WORLD", "SIM", "ART", "SYS"],
            "ART",
            {"work": "shader"},
            owner,
            "shader maps to ART.",
        ),
        _raw(
            "w-own-migrate",
            "work_code_owner",
            "owner",
            "owner",
            "game_sim",
            "Policy: shader is ART, plot is WORLD, tick is SIM, migrate is SYS. Work is migrate. Which worker owns this task?",
            ["ART", "SYS", "WORLD", "SIM"],
            "SYS",
            {"work": "migrate"},
            owner,
            "migrate maps to SYS.",
        ),
        _raw(
            "w-reach-yes",
            "directed_reach",
            "reachability",
            "reach",
            "epistemics",
            "Directed edges are P to Q and Q to R. Start is P. Goal is R. Is the goal reachable?",
            ["unreachable", "reachable"],
            "reachable",
            {"edges": [["P", "Q"], ["Q", "R"]], "start": "P", "goal": "R"},
            {"op": "reach", "if_true": "reachable", "if_false": "unreachable"},
            "P reaches Q and Q reaches R.",
        ),
        _raw(
            "w-reach-no",
            "directed_reach",
            "reachability",
            "reach",
            "epistemics",
            "Directed edges are P to Q and Q to R. Start is P. Goal is S. Is the goal reachable?",
            ["reachable", "unreachable"],
            "unreachable",
            {"edges": [["P", "Q"], ["Q", "R"]], "start": "P", "goal": "S"},
            {"op": "reach", "if_true": "reachable", "if_false": "unreachable"},
            "No edge reaches S.",
        ),
        _raw(
            "w-cycle-yes",
            "directed_cycle",
            "cycle",
            "cycle",
            "epistemics",
            "Directed edges are P to Q and Q to P. Does the graph contain a cycle?",
            ["no", "yes"],
            "yes",
            {"edges": [["P", "Q"], ["Q", "P"]]},
            {"op": "cycle", "if_true": "yes", "if_false": "no"},
            "P and Q point at each other.",
        ),
        _raw(
            "w-cycle-no",
            "directed_cycle",
            "cycle",
            "cycle",
            "epistemics",
            "Directed edges are P to Q and Q to R. Does the graph contain a cycle?",
            ["yes", "no"],
            "no",
            {"edges": [["P", "Q"], ["Q", "R"]]},
            {"op": "cycle", "if_true": "yes", "if_false": "no"},
            "The chain does not return.",
        ),
        _raw(
            "w-sum-ok",
            "parts_sum_to_total",
            "conservation",
            "sum",
            "economy",
            "Parts are 3 and 5. Total is 8. Quantities are conserved when the parts sum to the total. Are the quantities conserved?",
            ["violated", "conserved"],
            "conserved",
            {"parts": [3, 5], "total": 8},
            {"op": "sum_eq", "parts": "parts", "total": "total", "if_true": "conserved", "if_false": "violated"},
            "3 plus 5 equals 8.",
        ),
        _raw(
            "w-sum-bad",
            "parts_sum_to_total",
            "conservation",
            "sum",
            "economy",
            "Parts are 3 and 4. Total is 8. Quantities are conserved when the parts sum to the total. Are the quantities conserved?",
            ["conserved", "violated"],
            "violated",
            {"parts": [3, 4], "total": 8},
            {"op": "sum_eq", "parts": "parts", "total": "total", "if_true": "conserved", "if_false": "violated"},
            "3 plus 4 is 7, not 8.",
        ),
        _raw(
            "w-mono-bad",
            "lock_ids_increase",
            "lock_order",
            "lock",
            "software",
            "Lock ids were acquired as 4 then 2. Acquisition is valid when ids strictly increase. Is this acquisition valid?",
            ["valid", "invalid"],
            "invalid",
            {"seq": [4, 2]},
            {"op": "monotonic", "key": "seq", "if_true": "valid", "if_false": "invalid"},
            "4 then 2 decreases.",
        ),
        _raw(
            "w-mono-ok",
            "lock_ids_increase",
            "lock_order",
            "lock",
            "software",
            "Lock ids were acquired as 2 then 4. Acquisition is valid when ids strictly increase. Is this acquisition valid?",
            ["invalid", "valid"],
            "valid",
            {"seq": [2, 4]},
            {"op": "monotonic", "key": "seq", "if_true": "valid", "if_false": "invalid"},
            "2 then 4 increases.",
        ),
        _raw(
            "w-prior-yes",
            "ship_needs_payment",
            "event_causally_valid",
            "prior",
            "epistemics",
            "Priors include payment_captured. A shipment is valid when priors contain payment_captured. Is the shipment valid?",
            ["invalid", "valid"],
            "valid",
            {"priors": ["order_created", "payment_captured"]},
            {"op": "contains", "key": "priors", "item": "payment_captured", "if_true": "valid", "if_false": "invalid"},
            "payment_captured is already recorded.",
        ),
        _raw(
            "w-prior-no",
            "ship_needs_payment",
            "event_causally_valid",
            "prior",
            "epistemics",
            "Priors include only order_created. A shipment is valid when priors contain payment_captured. Is the shipment valid?",
            ["valid", "invalid"],
            "invalid",
            {"priors": ["order_created"]},
            {"op": "contains", "key": "priors", "item": "payment_captured", "if_true": "valid", "if_false": "invalid"},
            "payment_captured is absent.",
        ),
    ]
